CREATE TABLE service_credentials (
  id VARCHAR(36) PRIMARY KEY,
  enterprise_id VARCHAR(36) NOT NULL,
  application_id VARCHAR(36) NOT NULL,
  application_instance_id VARCHAR(36) NOT NULL,
  name VARCHAR(128) NOT NULL,
  secret_digest CHAR(64) NOT NULL,
  scopes TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  rotation_lineage VARCHAR(64) NOT NULL,
  rotated_from_id VARCHAR(36) NOT NULL,
  expires_at TIMESTAMP(6) NOT NULL,
  overlap_until TIMESTAMP(6) NULL,
  last_used_at TIMESTAMP(6) NULL,
  revoked_at TIMESTAMP(6) NULL,
  version BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  KEY idx_service_credentials_instance (enterprise_id, application_instance_id),
  KEY idx_service_credentials_lineage (rotation_lineage),
  CONSTRAINT fk_service_credentials_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises(enterprise_id),
  CONSTRAINT fk_service_credentials_application FOREIGN KEY (application_id) REFERENCES applications(id),
  CONSTRAINT fk_service_credentials_instance FOREIGN KEY (application_instance_id) REFERENCES application_instances(id)
) ENGINE=InnoDB;
