// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	adminRead "github.com/xfzen/ecp/server/api/internal/handler/adminRead"
	adminWrite "github.com/xfzen/ecp/server/api/internal/handler/adminWrite"
	authPublic "github.com/xfzen/ecp/server/api/internal/handler/authPublic"
	connectorMachine "github.com/xfzen/ecp/server/api/internal/handler/connectorMachine"
	metaPublic "github.com/xfzen/ecp/server/api/internal/handler/metaPublic"
	"github.com/xfzen/ecp/server/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminSession},
			[]rest.Route{
				{
					// Current admin session
					Method:  http.MethodGet,
					Path:    "/auth/session",
					Handler: adminRead.CurrentSessionHandler(serverCtx),
				},
				{
					// List admin sessions
					Method:  http.MethodGet,
					Path:    "/auth/sessions",
					Handler: adminRead.ListSessionsHandler(serverCtx),
				},
				{
					// List direct group members
					Method:  http.MethodGet,
					Path:    "/identity/groups/:id/members",
					Handler: adminRead.ListDirectGroupMembersHandler(serverCtx),
				},
				{
					// Get instance security controls
					Method:  http.MethodGet,
					Path:    "/instances/:id/security",
					Handler: adminRead.GetSecurityConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminSession, serverCtx.CSRF, serverCtx.IdempotencyHeaders, serverCtx.RateLimit},
			[]rest.Route{
				{
					// Register an application
					Method:  http.MethodPost,
					Path:    "/applications",
					Handler: adminWrite.RegisterApplicationHandler(serverCtx),
				},
				{
					// Register an application instance
					Method:  http.MethodPost,
					Path:    "/applications/:id/instances",
					Handler: adminWrite.RegisterInstanceHandler(serverCtx),
				},
				{
					// Put a product manifest
					Method:  http.MethodPut,
					Path:    "/applications/:id/manifest",
					Handler: adminWrite.PutManifestHandler(serverCtx),
				},
				{
					// End the current admin session
					Method:  http.MethodPost,
					Path:    "/auth/logout",
					Handler: adminWrite.LogoutHandler(serverCtx),
				},
				{
					// Revoke an admin session
					Method:  http.MethodPost,
					Path:    "/auth/sessions/:id/revoke",
					Handler: adminWrite.RevokeSessionHandler(serverCtx),
				},
				{
					// Create an ECP-managed direct group
					Method:  http.MethodPost,
					Path:    "/identity/groups",
					Handler: adminWrite.CreateIdentityGroupHandler(serverCtx),
				},
				{
					// Add one direct member to an ECP-managed group
					Method:  http.MethodPost,
					Path:    "/identity/groups/:id/members",
					Handler: adminWrite.AddDirectGroupMemberHandler(serverCtx),
				},
				{
					// Synchronize a directory-managed direct group
					Method:  http.MethodPost,
					Path:    "/identity/groups/directory/:externalId/sync",
					Handler: adminWrite.SyncDirectoryGroupHandler(serverCtx),
				},
				{
					// Admit a verified external identity
					Method:  http.MethodPost,
					Path:    "/identity/jit",
					Handler: adminWrite.AdmitJITHandler(serverCtx),
				},
				{
					// Block a principal locally
					Method:  http.MethodPost,
					Path:    "/identity/principals/:id/block",
					Handler: adminWrite.BlockPrincipalHandler(serverCtx),
				},
				{
					// Reconcile projected Casdoor policies
					Method:  http.MethodPost,
					Path:    "/instances/:id/policies/reconcile",
					Handler: adminWrite.ReconcilePoliciesHandler(serverCtx),
				},
				{
					// Put instance security controls
					Method:  http.MethodPut,
					Path:    "/instances/:id/security",
					Handler: adminWrite.PutSecurityConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// Complete an OIDC login transaction
					Method:  http.MethodGet,
					Path:    "/auth/callback",
					Handler: authPublic.AuthCallbackHandler(serverCtx),
				},
				{
					// Begin an OIDC login transaction
					Method:  http.MethodGet,
					Path:    "/auth/start",
					Handler: authPublic.AuthStartHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ConnectorMachine, serverCtx.IdempotencyHeaders, serverCtx.RateLimit},
			[]rest.Route{
				{
					// Authorize one product operation
					Method:  http.MethodPost,
					Path:    "/access/authorize",
					Handler: connectorMachine.AuthorizeHandler(serverCtx),
				},
				{
					// Authorize a batch of product operations
					Method:  http.MethodPost,
					Path:    "/access/batch",
					Handler: connectorMachine.BatchAuthorizeHandler(serverCtx),
				},
				{
					// Exchange a one-time product login transaction
					Method:  http.MethodPost,
					Path:    "/connector/auth/exchange",
					Handler: connectorMachine.ExchangeProductLoginHandler(serverCtx),
				},
				{
					// Register a product connector
					Method:  http.MethodPost,
					Path:    "/connectors/register",
					Handler: connectorMachine.RegisterConnectorHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Service health
				Method:  http.MethodGet,
				Path:    "/meta/health",
				Handler: metaPublic.HealthHandler(serverCtx),
			},
			{
				// Build and contract version
				Method:  http.MethodGet,
				Path:    "/meta/version",
				Handler: metaPublic.VersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
