// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ecp "github.com/xfzen/ecp/server/api/internal/handler/ecp"
	"github.com/xfzen/ecp/server/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Register an application
				Method:  http.MethodPost,
				Path:    "/applications",
				Handler: ecp.RegisterApplicationHandler(serverCtx),
			},
			{
				// Register an application instance
				Method:  http.MethodPost,
				Path:    "/applications/:id/instances",
				Handler: ecp.RegisterInstanceHandler(serverCtx),
			},
			{
				// Put a product manifest
				Method:  http.MethodPut,
				Path:    "/applications/:id/manifest",
				Handler: ecp.PutManifestHandler(serverCtx),
			},
			{
				// Register a product connector
				Method:  http.MethodPost,
				Path:    "/connectors/register",
				Handler: ecp.RegisterConnectorHandler(serverCtx),
			},
			{
				// Create an ECP-managed direct group
				Method:  http.MethodPost,
				Path:    "/identity/groups",
				Handler: ecp.CreateIdentityGroupHandler(serverCtx),
			},
			{
				// Add one direct member to an ECP-managed group
				Method:  http.MethodPost,
				Path:    "/identity/groups/:id/members",
				Handler: ecp.AddDirectGroupMemberHandler(serverCtx),
			},
			{
				// List direct group members
				Method:  http.MethodGet,
				Path:    "/identity/groups/:id/members",
				Handler: ecp.ListDirectGroupMembersHandler(serverCtx),
			},
			{
				// Synchronize a directory-managed direct group
				Method:  http.MethodPost,
				Path:    "/identity/groups/directory/:externalId/sync",
				Handler: ecp.SyncDirectoryGroupHandler(serverCtx),
			},
			{
				// Admit a verified external identity
				Method:  http.MethodPost,
				Path:    "/identity/jit",
				Handler: ecp.AdmitJITHandler(serverCtx),
			},
			{
				// Block a principal locally
				Method:  http.MethodPost,
				Path:    "/identity/principals/:id/block",
				Handler: ecp.BlockPrincipalHandler(serverCtx),
			},
			{
				// Service health
				Method:  http.MethodGet,
				Path:    "/meta/health",
				Handler: ecp.HealthHandler(serverCtx),
			},
			{
				// Build and contract version
				Method:  http.MethodGet,
				Path:    "/meta/version",
				Handler: ecp.VersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
