// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ecp "github.com/xfzen/ecp/server/api/internal/handler/ecp"
	"github.com/xfzen/ecp/server/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Register an application
				Method:  http.MethodPost,
				Path:    "/applications",
				Handler: ecp.RegisterApplicationHandler(serverCtx),
			},
			{
				// Register an application instance
				Method:  http.MethodPost,
				Path:    "/applications/:id/instances",
				Handler: ecp.RegisterInstanceHandler(serverCtx),
			},
			{
				// Put a product manifest
				Method:  http.MethodPut,
				Path:    "/applications/:id/manifest",
				Handler: ecp.PutManifestHandler(serverCtx),
			},
			{
				// Register a product connector
				Method:  http.MethodPost,
				Path:    "/connectors/register",
				Handler: ecp.RegisterConnectorHandler(serverCtx),
			},
			{
				// Service health
				Method:  http.MethodGet,
				Path:    "/meta/health",
				Handler: ecp.HealthHandler(serverCtx),
			},
			{
				// Build and contract version
				Method:  http.MethodGet,
				Path:    "/meta/version",
				Handler: ecp.VersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
