import React from 'react';
import PropTypes from 'prop-types';
import {
  AndroidOutlined,
  ApiOutlined,
  AppleOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowUpOutlined,
  AppstoreOutlined,
  BarsOutlined,
  CalendarOutlined,
  CameraOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseOutlined,
  CloudOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CopyOutlined,
  CustomerServiceOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DesktopOutlined,
  DownOutlined,
  EditOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  ExclamationCircleOutlined,
  EyeOutlined,
  FileOutlined,
  FileTextOutlined,
  FolderOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  ForkOutlined,
  GlobalOutlined,
  HddOutlined,
  IdcardOutlined,
  InboxOutlined,
  LineChartOutlined,
  LockOutlined,
  LogoutOutlined,
  MailOutlined,
  MedicineBoxOutlined,
  MinusCircleOutlined,
  MobileOutlined,
  NotificationOutlined,
  PayCircleOutlined,
  PictureOutlined,
  PlayCircleOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  PoweroffOutlined,
  QuestionCircleOutlined,
  ReloadOutlined,
  RocketOutlined,
  SafetyOutlined,
  SaveOutlined,
  SearchOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShoppingCartOutlined,
  StarOutlined,
  SwapOutlined,
  TagOutlined,
  TeamOutlined,
  ToolOutlined,
  UnlockOutlined,
  UpOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WifiOutlined
} from '@ant-design/icons';

const icons = {
  'android-o': AndroidOutlined,
  api: ApiOutlined,
  'apple-o': AppleOutlined,
  'arrow-down': ArrowDownOutlined,
  'arrow-left': ArrowLeftOutlined,
  'arrow-up': ArrowUpOutlined,
  'appstore-o': AppstoreOutlined,
  bars: BarsOutlined,
  calendar: CalendarOutlined,
  'camera-o': CameraOutlined,
  check: CheckOutlined,
  'clock-circle-o': ClockCircleOutlined,
  close: CloseOutlined,
  'cloud-o': CloudOutlined,
  'code-o': CodeOutlined,
  coffee: CoffeeOutlined,
  copy: CopyOutlined,
  'customer-service': CustomerServiceOutlined,
  database: DatabaseOutlined,
  delete: DeleteOutlined,
  desktop: DesktopOutlined,
  down: DownOutlined,
  edit: EditOutlined,
  ellipsis: EllipsisOutlined,
  'environment-o': EnvironmentOutlined,
  'exclamation-circle-o': ExclamationCircleOutlined,
  'eye-o': EyeOutlined,
  file: FileOutlined,
  'file-text': FileTextOutlined,
  folder: FolderOutlined,
  'folder-add': FolderAddOutlined,
  'folder-open': FolderOpenOutlined,
  fork: ForkOutlined,
  global: GlobalOutlined,
  hdd: HddOutlined,
  idcard: IdcardOutlined,
  inbox: InboxOutlined,
  'line-chart': LineChartOutlined,
  lock: LockOutlined,
  logout: LogoutOutlined,
  mail: MailOutlined,
  'medicine-box': MedicineBoxOutlined,
  'minus-circle-o': MinusCircleOutlined,
  mobile: MobileOutlined,
  notification: NotificationOutlined,
  'pay-circle-o': PayCircleOutlined,
  picture: PictureOutlined,
  'play-circle-o': PlayCircleOutlined,
  plus: PlusOutlined,
  'plus-circle': PlusCircleOutlined,
  poweroff: PoweroffOutlined,
  'question-circle': QuestionCircleOutlined,
  'question-circle-o': QuestionCircleOutlined,
  reload: ReloadOutlined,
  rocket: RocketOutlined,
  safety: SafetyOutlined,
  save: SaveOutlined,
  search: SearchOutlined,
  setting: SettingOutlined,
  'share-alt': ShareAltOutlined,
  'shopping-cart': ShoppingCartOutlined,
  star: StarOutlined,
  'star-o': StarOutlined,
  swap: SwapOutlined,
  'tag-o': TagOutlined,
  team: TeamOutlined,
  tool: ToolOutlined,
  unlock: UnlockOutlined,
  up: UpOutlined,
  upload: UploadOutlined,
  user: UserOutlined,
  'video-camera': VideoCameraOutlined,
  wifi: WifiOutlined
};

const LegacyIcon = React.forwardRef(function LegacyIcon({ type, icon: _icon, component: _component, ...props }, ref) {
  const IconComponent = icons[type] || QuestionCircleOutlined;
  return <IconComponent ref={ref} {...props} />;
});

LegacyIcon.propTypes = {
  type: PropTypes.string
};

export default LegacyIcon;
