appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = postgres
dataSourceName = "user=casdoor_runtime password=__CASDOOR_DB_PASSWORD__ host=postgres port=5432 sslmode=disable dbname=casdoor_db"
dbName = casdoor_db
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin = "http://127.0.0.1:4002"
originFrontend = "http://127.0.0.1:4002"
