// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddGroupMemberReq struct {
	GroupID      string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
	PrincipalID  string `json:"principal_id"`
}

type AdmitJITReq struct {
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	Issuer        string `json:"issuer"`
	Subject       string `json:"subject"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	DisplayName   string `json:"display_name,optional"`
}

type ApplicationResp struct {
	ID           string `json:"id"`
	EnterpriseID string `json:"enterprise_id"`
	Key          string `json:"key"`
	Name         string `json:"name"`
	Status       string `json:"status"`
	Version      uint64 `json:"version"`
}

type AuthCallbackReq struct {
	State string `form:"state"`
	Code  string `form:"code"`
}

type AuthStartReq struct {
	EnterpriseID          string `form:"enterprise_id"`
	OIDCClientID          string `form:"oidc_client_id"`
	ApplicationInstanceID string `form:"application_instance_id,optional"`
	Kind                  string `form:"kind"`
	RedirectURI           string `form:"redirect_uri"`
}

type AuthStartResp struct {
	TransactionID string `json:"transaction_id"`
	State         string `json:"state"`
	Nonce         string `json:"nonce"`
	CodeChallenge string `json:"code_challenge"`
	ExpiresAt     int64  `json:"expires_at"`
}

type AuthorizationDecisionResp struct {
	Allow                     bool   `json:"allow"`
	Reason                    string `json:"reason"`
	LifecycleVersion          uint64 `json:"lifecycle_version"`
	IdentitySyncVersion       uint64 `json:"identity_sync_version"`
	IdentityFreshnessDeadline int64  `json:"identity_freshness_deadline"`
	PolicyVersion             uint64 `json:"policy_version"`
	AuthorizedResourceVersion uint64 `json:"authorized_resource_version"`
	SecurityConfigVersion     uint64 `json:"security_config_version"`
}

type AuthorizeReq struct {
	EnterpriseID          string   `json:"enterprise_id"`
	ApplicationInstanceID string   `json:"application_instance_id"`
	PrincipalID           string   `json:"principal_id"`
	PrincipalKind         string   `json:"principal_kind"`
	IdentityProvider      string   `json:"identity_provider"`
	PolicySubject         string   `json:"policy_subject"`
	DirectGroupIDs        []string `json:"direct_group_ids"`
	DirectGroupVersion    uint64   `json:"direct_group_version"`
	PolicyID              string   `json:"policy_id"`
	Action                string   `json:"action"`
	ResourceID            string   `json:"resource_id"`
	ResourceVersion       uint64   `json:"resource_version"`
}

type BatchAuthorizeReq struct {
	Requests []AuthorizeReq `json:"requests"`
}

type BatchAuthorizeResp struct {
	Decisions []AuthorizationDecisionResp `json:"decisions"`
}

type BlockPrincipalReq struct {
	PrincipalID  string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
}

type ConnectorResp struct {
	ID            string `json:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceID    string `json:"instance_id"`
	ConnectorKey  string `json:"connector_key"`
	Status        string `json:"status"`
	Version       uint64 `json:"version"`
}

type CreateGroupReq struct {
	EnterpriseID string `json:"enterprise_id"`
	Name         string `json:"name"`
}

type Empty struct {
}

type EnterpriseResp struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type GroupMembersResp struct {
	PrincipalIDs []string `json:"principal_ids"`
}

type GroupResp struct {
	ID                  string `json:"id"`
	EnterpriseID        string `json:"enterprise_id"`
	Provider            string `json:"provider"`
	ExternalID          string `json:"external_id"`
	Name                string `json:"name"`
	ManagementMode      string `json:"management_mode"`
	DirectMemberVersion uint64 `json:"direct_member_version"`
	Status              string `json:"status"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type InstanceResp struct {
	ID            string `json:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceKey   string `json:"instance_key"`
	Environment   string `json:"environment"`
	CanonicalURL  string `json:"canonical_url"`
	Status        string `json:"status"`
	Version       uint64 `json:"version"`
}

type LifecycleResp struct {
	PrincipalID string `json:"principal_id"`
	State       string `json:"state"`
	Version     uint64 `json:"version"`
}

type ListGroupMembersReq struct {
	GroupID      string `path:"id"`
	EnterpriseID string `form:"enterprise_id"`
}

type ManifestResp struct {
	ApplicationID string `json:"application_id"`
	APIVersion    string `json:"api_version"`
	ManifestHash  string `json:"manifest_hash"`
	Version       uint64 `json:"version"`
}

type PolicyItem struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
	PType string `json:"ptype"`
	V0    string `json:"v0"`
	V1    string `json:"v1"`
	V2    string `json:"v2"`
	V3    string `json:"v3,optional"`
	V4    string `json:"v4,optional"`
	V5    string `json:"v5,optional"`
}

type PolicyProjectionResp struct {
	ApplicationInstanceID string `json:"application_instance_id"`
	NormalizedHash        string `json:"normalized_hash"`
	ManifestVersion       uint64 `json:"manifest_version"`
	PolicyVersion         uint64 `json:"policy_version"`
	ReconciliationState   string `json:"reconciliation_state"`
}

type PrincipalResp struct {
	ID              string `json:"id"`
	EnterpriseID    string `json:"enterprise_id"`
	Issuer          string `json:"issuer"`
	Subject         string `json:"subject"`
	NormalizedEmail string `json:"normalized_email"`
	DisplayName     string `json:"display_name"`
	Status          string `json:"status"`
	Version         uint64 `json:"version"`
}

type ProductLoginExchangeReq struct {
	Code string `json:"code"`
}

type ProductLoginExchangeResp struct {
	SessionToken string `json:"session_token"`
	CSRFToken    string `json:"csrf_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type PutManifestReq struct {
	ApplicationID string `path:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	APIVersion    string `json:"api_version"`
	Body          string `json:"body"`
}

type PutSecurityConfigReq struct {
	ApplicationInstanceID string `path:"id"`
	EnterpriseID          string `json:"enterprise_id"`
	PublicSharing         bool   `json:"public_sharing"`
	ExportEnabled         bool   `json:"export_enabled"`
	SecretExport          bool   `json:"secret_export"`
}

type ReconcilePoliciesReq struct {
	ApplicationInstanceID string       `path:"id"`
	EnterpriseID          string       `json:"enterprise_id"`
	ManifestVersion       uint64       `json:"manifest_version"`
	Policies              []PolicyItem `json:"policies"`
}

type RegisterApplicationReq struct {
	ID           string `json:"id"`
	EnterpriseID string `json:"enterprise_id"`
	Key          string `json:"key"`
	Name         string `json:"name"`
}

type RegisterConnectorReq struct {
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceID    string `json:"instance_id"`
	ConnectorKey  string `json:"connector_key"`
}

type RegisterEnterpriseReq struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RegisterInstanceReq struct {
	ApplicationID string `path:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	InstanceKey   string `json:"instance_key"`
	Environment   string `json:"environment,optional"`
	CanonicalURL  string `json:"canonical_url"`
}

type RevokeSessionReq struct {
	SessionID    string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
}

type SecurityConfigReq struct {
	EnterpriseID          string `form:"enterprise_id"`
	ApplicationInstanceID string `path:"id"`
}

type SecurityConfigResp struct {
	EnterpriseID          string `json:"enterprise_id"`
	ApplicationInstanceID string `json:"application_instance_id"`
	PublicSharing         bool   `json:"public_sharing"`
	ExportEnabled         bool   `json:"export_enabled"`
	SecretExport          bool   `json:"secret_export"`
	Version               uint64 `json:"version"`
}

type SessionListReq struct {
	EnterpriseID string `form:"enterprise_id"`
}

type SessionListResp struct {
	Sessions []SessionSummaryResp `json:"sessions"`
}

type SessionSummaryResp struct {
	ID                    string `json:"id"`
	EnterpriseID          string `json:"enterprise_id"`
	PrincipalID           string `json:"principal_id"`
	ApplicationInstanceID string `json:"application_instance_id,optional"`
	Kind                  string `json:"kind"`
	ExpiresAt             int64  `json:"expires_at"`
	Revoked               bool   `json:"revoked"`
}

type SyncDirectoryGroupReq struct {
	ExternalID   string   `path:"externalId"`
	EnterpriseID string   `json:"enterprise_id"`
	Provider     string   `json:"provider"`
	Name         string   `json:"name"`
	PrincipalIDs []string `json:"principal_ids"`
}

type VersionResp struct {
	Version    string `json:"version"`
	APIVersion string `json:"api_version"`
}
