// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddGroupMemberReq struct {
	GroupID      string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
	PrincipalID  string `json:"principal_id"`
}

type AdmitJITReq struct {
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	Issuer        string `json:"issuer"`
	Subject       string `json:"subject"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	DisplayName   string `json:"display_name,optional"`
}

type ApplicationResp struct {
	ID           string `json:"id"`
	EnterpriseID string `json:"enterprise_id"`
	Key          string `json:"key"`
	Name         string `json:"name"`
	Status       string `json:"status"`
	Version      uint64 `json:"version"`
}

type AuthCallbackReq struct {
	State string `form:"state"`
	Code  string `form:"code"`
}

type AuthStartReq struct {
	EnterpriseID          string `form:"enterprise_id"`
	OIDCClientID          string `form:"oidc_client_id"`
	ApplicationInstanceID string `form:"application_instance_id,optional"`
	Kind                  string `form:"kind"`
	RedirectURI           string `form:"redirect_uri"`
}

type AuthStartResp struct {
	TransactionID string `json:"transaction_id"`
	State         string `json:"state"`
	Nonce         string `json:"nonce"`
	CodeChallenge string `json:"code_challenge"`
	ExpiresAt     int64  `json:"expires_at"`
}

type BlockPrincipalReq struct {
	PrincipalID  string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
}

type ConnectorResp struct {
	ID            string `json:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceID    string `json:"instance_id"`
	ConnectorKey  string `json:"connector_key"`
	Status        string `json:"status"`
	Version       uint64 `json:"version"`
}

type CreateGroupReq struct {
	EnterpriseID string `json:"enterprise_id"`
	Name         string `json:"name"`
}

type Empty struct {
}

type EnterpriseResp struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type GroupMembersResp struct {
	PrincipalIDs []string `json:"principal_ids"`
}

type GroupResp struct {
	ID                  string `json:"id"`
	EnterpriseID        string `json:"enterprise_id"`
	Provider            string `json:"provider"`
	ExternalID          string `json:"external_id"`
	Name                string `json:"name"`
	ManagementMode      string `json:"management_mode"`
	DirectMemberVersion uint64 `json:"direct_member_version"`
	Status              string `json:"status"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type InstanceResp struct {
	ID            string `json:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceKey   string `json:"instance_key"`
	Environment   string `json:"environment"`
	CanonicalURL  string `json:"canonical_url"`
	Status        string `json:"status"`
	Version       uint64 `json:"version"`
}

type LifecycleResp struct {
	PrincipalID string `json:"principal_id"`
	State       string `json:"state"`
	Version     uint64 `json:"version"`
}

type ListGroupMembersReq struct {
	GroupID      string `path:"id"`
	EnterpriseID string `form:"enterprise_id"`
}

type ManifestResp struct {
	ApplicationID string `json:"application_id"`
	APIVersion    string `json:"api_version"`
	ManifestHash  string `json:"manifest_hash"`
	Version       uint64 `json:"version"`
}

type PrincipalResp struct {
	ID              string `json:"id"`
	EnterpriseID    string `json:"enterprise_id"`
	Issuer          string `json:"issuer"`
	Subject         string `json:"subject"`
	NormalizedEmail string `json:"normalized_email"`
	DisplayName     string `json:"display_name"`
	Status          string `json:"status"`
	Version         uint64 `json:"version"`
}

type ProductLoginExchangeReq struct {
	Code string `json:"code"`
}

type ProductLoginExchangeResp struct {
	SessionToken string `json:"session_token"`
	CSRFToken    string `json:"csrf_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type PutManifestReq struct {
	ApplicationID string `path:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	APIVersion    string `json:"api_version"`
	Body          string `json:"body"`
}

type RegisterApplicationReq struct {
	ID           string `json:"id"`
	EnterpriseID string `json:"enterprise_id"`
	Key          string `json:"key"`
	Name         string `json:"name"`
}

type RegisterConnectorReq struct {
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceID    string `json:"instance_id"`
	ConnectorKey  string `json:"connector_key"`
}

type RegisterEnterpriseReq struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RegisterInstanceReq struct {
	ApplicationID string `path:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	InstanceKey   string `json:"instance_key"`
	Environment   string `json:"environment,optional"`
	CanonicalURL  string `json:"canonical_url"`
}

type RevokeSessionReq struct {
	SessionID    string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
}

type SessionListReq struct {
	EnterpriseID string `form:"enterprise_id"`
}

type SessionListResp struct {
	Sessions []SessionSummaryResp `json:"sessions"`
}

type SessionSummaryResp struct {
	ID                    string `json:"id"`
	EnterpriseID          string `json:"enterprise_id"`
	PrincipalID           string `json:"principal_id"`
	ApplicationInstanceID string `json:"application_instance_id,optional"`
	Kind                  string `json:"kind"`
	ExpiresAt             int64  `json:"expires_at"`
	Revoked               bool   `json:"revoked"`
}

type SyncDirectoryGroupReq struct {
	ExternalID   string   `path:"externalId"`
	EnterpriseID string   `json:"enterprise_id"`
	Provider     string   `json:"provider"`
	Name         string   `json:"name"`
	PrincipalIDs []string `json:"principal_ids"`
}

type VersionResp struct {
	Version    string `json:"version"`
	APIVersion string `json:"api_version"`
}
