// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AckDelegationKeySetReq struct {
	Version        uint64   `json:"version"`
	AcceptedKeyIDs []string `json:"accepted_key_ids"`
}

type AddGroupMemberReq struct {
	GroupID      string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
	PrincipalID  string `json:"principal_id"`
}

type AdminEnterpriseReq struct {
	EnterpriseID string `form:"enterprise_id"`
}

type AdminEntityReq struct {
	EnterpriseID string `form:"enterprise_id"`
	ID           string `path:"id"`
}

type AdmitJITReq struct {
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	Issuer        string `json:"issuer"`
	Subject       string `json:"subject"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	DisplayName   string `json:"display_name,optional"`
}

type ApplicationListResp struct {
	Applications []ApplicationResp `json:"applications"`
}

type ApplicationResp struct {
	ID           string `json:"id"`
	EnterpriseID string `json:"enterprise_id"`
	Key          string `json:"key"`
	Name         string `json:"name"`
	Status       string `json:"status"`
	Version      uint64 `json:"version"`
}

type AuditEventResp struct {
	Sequence              uint64 `json:"sequence"`
	ID                    string `json:"id"`
	EnterpriseID          string `json:"enterprise_id"`
	ApplicationInstanceID string `json:"application_instance_id"`
	OperationID           string `json:"operation_id"`
	Stage                 string `json:"stage"`
	ActorID               string `json:"actor_id"`
	ActorKind             string `json:"actor_kind"`
	Action                string `json:"action"`
	ResourceType          string `json:"resource_type"`
	ResourceID            string `json:"resource_id"`
	Outcome               string `json:"outcome"`
	Reason                string `json:"reason"`
	SafeDiff              string `json:"safe_diff"`
	OccurredAt            int64  `json:"occurred_at"`
}

type AuditExportReq struct {
	EnterpriseID          string `json:"enterprise_id"`
	ApplicationInstanceID string `json:"application_instance_id,optional"`
	SequenceAfter         uint64 `json:"sequence_after,optional"`
	Limit                 int    `json:"limit,optional"`
}

type AuditExportResp struct {
	Version       uint64 `json:"version"`
	SequenceStart uint64 `json:"sequence_start"`
	SequenceEnd   uint64 `json:"sequence_end"`
	EventCount    uint64 `json:"event_count"`
	CanonicalHash string `json:"canonical_hash"`
	GeneratedAt   int64  `json:"generated_at"`
}

type AuditQueryReq struct {
	EnterpriseID          string `form:"enterprise_id"`
	ApplicationInstanceID string `form:"application_instance_id,optional"`
	OperationID           string `form:"operation_id,optional"`
	SequenceAfter         uint64 `form:"sequence_after,optional"`
	Limit                 int    `form:"limit,optional"`
}

type AuditQueryResp struct {
	Events []AuditEventResp `json:"events"`
}

type AuthCallbackReq struct {
	State string `form:"state"`
	Code  string `form:"code"`
}

type AuthStartReq struct {
}

type AuthStartResp struct {
	TransactionID    string `json:"transaction_id"`
	State            string `json:"state"`
	Nonce            string `json:"nonce"`
	CodeChallenge    string `json:"code_challenge"`
	AuthorizationURL string `json:"authorization_url"`
	ExpiresAt        int64  `json:"expires_at"`
}

type AuthenticateServiceCredentialReq struct {
	Credential      string `json:"credential"`
	ResourceType    string `json:"resource_type"`
	ResourceID      string `json:"resource_id"`
	Action          string `json:"action"`
	ResourceVersion uint64 `json:"resource_version"`
}

type AuthenticateServiceCredentialResp struct {
	PrincipalID string                    `json:"principal_id"`
	Decision    AuthorizationDecisionResp `json:"decision"`
}

type AuthorizationDecisionResp struct {
	Allow                     bool   `json:"allow"`
	Reason                    string `json:"reason"`
	LifecycleVersion          uint64 `json:"lifecycle_version"`
	IdentitySyncVersion       uint64 `json:"identity_sync_version"`
	IdentityFreshnessDeadline int64  `json:"identity_freshness_deadline"`
	PolicyVersion             uint64 `json:"policy_version"`
	AuthorizedResourceVersion uint64 `json:"authorized_resource_version"`
	SecurityConfigVersion     uint64 `json:"security_config_version"`
}

type AuthorizeReq struct {
	EnterpriseID          string   `json:"enterprise_id"`
	ApplicationInstanceID string   `json:"application_instance_id"`
	PrincipalID           string   `json:"principal_id"`
	PrincipalKind         string   `json:"principal_kind,optional"`
	IdentityProvider      string   `json:"identity_provider,optional"`
	PolicySubject         string   `json:"policy_subject,optional"`
	DirectGroupIDs        []string `json:"direct_group_ids,optional"`
	DirectGroupVersion    uint64   `json:"direct_group_version,optional"`
	Action                string   `json:"action"`
	ResourceType          string   `json:"resource_type"`
	ResourceID            string   `json:"resource_id"`
	ResourceVersion       uint64   `json:"resource_version"`
}

type BackupStatusReq struct {
	EnterpriseID string `form:"enterprise_id"`
}

type BackupStatusResp struct {
	State         string `json:"state"`
	BackupID      string `json:"backup_id,optional"`
	ManifestHash  string `json:"manifest_hash,optional"`
	FailureReason string `json:"failure_reason,optional"`
	StartedAt     int64  `json:"started_at,optional"`
	CompletedAt   int64  `json:"completed_at,optional"`
	VerifiedAt    int64  `json:"verified_at,optional"`
}

type BatchAuthorizeReq struct {
	Requests []AuthorizeReq `json:"requests"`
}

type BatchAuthorizeResp struct {
	Decisions []AuthorizationDecisionResp `json:"decisions"`
}

type BlockPrincipalReq struct {
	PrincipalID  string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
}

type ConnectorAuditEvent struct {
	OperationID  string            `json:"operation_id"`
	Action       string            `json:"action"`
	ResourceType string            `json:"resource_type"`
	ResourceID   string            `json:"resource_id"`
	Outcome      string            `json:"outcome"`
	OccurredAt   int64             `json:"occurred_at"`
	SafeDiff     map[string]string `json:"safe_diff,optional"`
}

type ConnectorHeartbeatReq struct {
	InstanceID string `json:"instance_id"`
	Version    string `json:"version"`
	ObservedAt int64  `json:"observed_at"`
}

type ConnectorHeartbeatResp struct {
	Accepted bool `json:"accepted"`
}

type ConnectorResp struct {
	ID               string               `json:"id"`
	EnterpriseID     string               `json:"enterprise_id"`
	ApplicationID    string               `json:"application_id"`
	InstanceID       string               `json:"instance_id"`
	ConnectorKey     string               `json:"connector_key"`
	Status           string               `json:"status"`
	Version          uint64               `json:"version"`
	RootFingerprint  string               `json:"root_fingerprint"`
	DelegationKeySet DelegationKeySetResp `json:"delegation_key_set"`
}

type CreateCredentialReq struct {
	EnterpriseID          string                `json:"enterprise_id"`
	ApplicationID         string                `json:"application_id"`
	ApplicationInstanceID string                `json:"application_instance_id"`
	Name                  string                `json:"name"`
	Scopes                []CredentialScopeItem `json:"scopes"`
	LifetimeSeconds       int64                 `json:"lifetime_seconds"`
}

type CreateGroupReq struct {
	EnterpriseID string `json:"enterprise_id"`
	Name         string `json:"name"`
}

type CredentialIDReq struct {
	ID string `path:"id"`
}

type CredentialResp struct {
	ID                    string                `json:"id"`
	EnterpriseID          string                `json:"enterprise_id"`
	ApplicationID         string                `json:"application_id"`
	ApplicationInstanceID string                `json:"application_instance_id"`
	Name                  string                `json:"name"`
	Secret                string                `json:"secret,optional"`
	Scopes                []CredentialScopeItem `json:"scopes"`
	Status                string                `json:"status"`
	RotationLineage       string                `json:"rotation_lineage"`
	ExpiresAt             int64                 `json:"expires_at"`
	OverlapUntil          int64                 `json:"overlap_until,optional"`
	LastUsedAt            int64                 `json:"last_used_at,optional"`
	Version               uint64                `json:"version"`
}

type CredentialScopeItem struct {
	ResourceType string   `json:"resource_type"`
	ResourceID   string   `json:"resource_id"`
	Actions      []string `json:"actions"`
}

type CredentialUsageReq struct {
	EnterpriseID          string `form:"enterprise_id"`
	ApplicationInstanceID string `path:"id"`
}

type CredentialUsageResp struct {
	Credentials []CredentialResp `json:"credentials"`
}

type DelegationKeySetResp struct {
	Algorithm    string `json:"alg"`
	SigningKeyID string `json:"signing_kid"`
	Payload      []byte `json:"payload"`
	Signature    string `json:"signature"`
}

type Empty struct {
}

type EnterpriseResp struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type GroupDetailResp struct {
	Group        GroupResp `json:"group"`
	PrincipalIDs []string  `json:"principal_ids"`
}

type GroupListResp struct {
	Groups []GroupResp `json:"groups"`
}

type GroupMembersResp struct {
	PrincipalIDs []string `json:"principal_ids"`
}

type GroupResp struct {
	ID                  string `json:"id"`
	EnterpriseID        string `json:"enterprise_id"`
	Provider            string `json:"provider"`
	ExternalID          string `json:"external_id"`
	Name                string `json:"name"`
	ManagementMode      string `json:"management_mode"`
	DirectMemberVersion uint64 `json:"direct_member_version"`
	Status              string `json:"status"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type IdentitySourceListResp struct {
	Sources []IdentitySourceResp `json:"sources"`
}

type IdentitySourceResp struct {
	ID                 string `json:"id"`
	Provider           string `json:"provider"`
	Version            uint64 `json:"version"`
	LastSuccessfulSync int64  `json:"last_successful_sync,optional"`
	FreshnessDeadline  int64  `json:"freshness_deadline,optional"`
	State              string `json:"state"`
	LastError          string `json:"last_error,optional"`
}

type IngestConnectorAuditReq struct {
	Events []ConnectorAuditEvent `json:"events"`
}

type InstanceListReq struct {
	EnterpriseID  string `form:"enterprise_id"`
	ApplicationID string `form:"application_id,optional"`
}

type InstanceListResp struct {
	Instances []InstanceResp `json:"instances"`
}

type InstanceOperationReq struct {
	EnterpriseID string `json:"enterprise_id"`
	InstanceID   string `path:"id"`
}

type InstanceResp struct {
	ID            string `json:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceKey   string `json:"instance_key"`
	Environment   string `json:"environment"`
	CanonicalURL  string `json:"canonical_url"`
	Status        string `json:"status"`
	Version       uint64 `json:"version"`
}

type LegacyIdentityResp struct {
	ID            string `json:"id"`
	ApplicationID string `json:"application_id"`
	LegacySource  string `json:"legacy_source"`
	LegacySubject string `json:"legacy_subject"`
	PrincipalID   string `json:"principal_id"`
}

type LifecycleChangeItem struct {
	PrincipalID string `json:"principal_id"`
	State       string `json:"state"`
	Version     uint64 `json:"version"`
}

type LifecyclePollReq struct {
	Cursor string `json:"cursor"`
	Limit  int    `json:"limit"`
}

type LifecyclePollResp struct {
	Changes    []LifecycleChangeItem `json:"changes"`
	NextCursor string                `json:"next_cursor"`
}

type LifecycleResp struct {
	PrincipalID string `json:"principal_id"`
	State       string `json:"state"`
	Version     uint64 `json:"version"`
}

type ListGroupMembersReq struct {
	GroupID      string `path:"id"`
	EnterpriseID string `form:"enterprise_id"`
}

type ManifestDetailResp struct {
	ApplicationID string `json:"application_id"`
	APIVersion    string `json:"api_version"`
	ManifestHash  string `json:"manifest_hash"`
	Body          string `json:"body"`
	Version       uint64 `json:"version"`
}

type ManifestResp struct {
	ApplicationID string `json:"application_id"`
	APIVersion    string `json:"api_version"`
	ManifestHash  string `json:"manifest_hash"`
	Version       uint64 `json:"version"`
}

type OffboardResp struct {
	ExportVerified        bool               `json:"export_verified"`
	SessionsRevoked       bool               `json:"sessions_revoked"`
	CredentialsRevoked    bool               `json:"credentials_revoked"`
	AuditFlushed          bool               `json:"audit_flushed"`
	ConnectorDisabled     bool               `json:"connector_disabled"`
	FinalLifecycleVersion uint64             `json:"final_lifecycle_version"`
	Export                PortableExportResp `json:"export"`
}

type PolicyItem struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
	PType string `json:"ptype"`
	V0    string `json:"v0"`
	V1    string `json:"v1"`
	V2    string `json:"v2"`
	V3    string `json:"v3,optional"`
	V4    string `json:"v4,optional"`
	V5    string `json:"v5,optional"`
}

type PolicyProjectionResp struct {
	ApplicationInstanceID string `json:"application_instance_id"`
	CasdoorPermissionID   string `json:"casdoor_permission_id"`
	NormalizedHash        string `json:"normalized_hash"`
	ManifestVersion       uint64 `json:"manifest_version"`
	PolicyVersion         uint64 `json:"policy_version"`
	ReconciliationState   string `json:"reconciliation_state"`
}

type PolicyVersionReq struct {
	InstanceID string `path:"id"`
}

type PolicyVersionResp struct {
	Version       uint64 `json:"version"`
	State         string `json:"state"`
	CanonicalHash string `json:"canonical_hash"`
}

type PortableExportResp struct {
	Version       uint64 `json:"version"`
	GeneratedAt   int64  `json:"generated_at"`
	CanonicalHash string `json:"canonical_hash"`
	Payload       string `json:"payload"`
}

type PrincipalListResp struct {
	Principals []PrincipalResp `json:"principals"`
}

type PrincipalResp struct {
	ID              string `json:"id"`
	EnterpriseID    string `json:"enterprise_id"`
	Issuer          string `json:"issuer"`
	Subject         string `json:"subject"`
	NormalizedEmail string `json:"normalized_email"`
	DisplayName     string `json:"display_name"`
	Status          string `json:"status"`
	Version         uint64 `json:"version"`
}

type ProductAuthCompleteReq struct {
	TransactionID string `json:"transaction_id"`
	State         string `json:"state"`
	PKCEVerifier  string `json:"pkce_verifier"`
	Nonce         string `json:"nonce"`
	Code          string `json:"code"`
}

type ProductAuthCompleteResp struct {
	ExchangeCode string `json:"exchange_code"`
	ExpiresAt    int64  `json:"expires_at"`
}

type ProductAuthStartReq struct {
	RedirectURI string `json:"redirect_uri"`
}

type ProductAuthStartResp struct {
	TransactionID    string `json:"transaction_id"`
	State            string `json:"state"`
	PKCEVerifier     string `json:"pkce_verifier"`
	Nonce            string `json:"nonce"`
	AuthorizationURL string `json:"authorization_url"`
	ExpiresAt        int64  `json:"expires_at"`
}

type ProductLoginExchangeReq struct {
	Code string `json:"code"`
}

type ProductLoginExchangeResp struct {
	SessionToken string `json:"session_token"`
	CSRFToken    string `json:"csrf_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type ProductResourceItem struct {
	Type     string `json:"type"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	ParentID string `json:"parent_id,optional"`
	Version  uint64 `json:"version"`
}

type ProductResourceListResp struct {
	Resources []ProductResourceItem `json:"resources"`
}

type ProductResourceReq struct {
	InstanceID   string `path:"id"`
	ResourceType string `path:"resourceType"`
	ResourceID   string `path:"resourceId"`
}

type ProductResourceResp struct {
	Resource ProductResourceItem `json:"resource"`
}

type ProductResourceSearchReq struct {
	InstanceID   string `path:"id"`
	ResourceType string `form:"resource_type,optional"`
	Query        string `form:"query,optional"`
	Limit        int    `form:"limit,optional"`
}

type PublishDelegationKeySetReq struct {
	Algorithm    string `json:"alg"`
	SigningKeyID string `json:"signing_kid"`
	Payload      []byte `json:"payload"`
	Signature    string `json:"signature"`
}

type PutLegacyIdentityReq struct {
	ApplicationID string `path:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	LegacySource  string `json:"legacy_source"`
	LegacySubject string `json:"legacy_subject"`
	PrincipalID   string `json:"principal_id"`
}

type PutManifestReq struct {
	ApplicationID string `path:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	APIVersion    string `json:"api_version"`
	Body          string `json:"body"`
}

type PutSecurityConfigReq struct {
	ApplicationInstanceID string `path:"id"`
	EnterpriseID          string `json:"enterprise_id"`
	PublicSharing         bool   `json:"public_sharing"`
	ExportEnabled         bool   `json:"export_enabled"`
	SecretExport          bool   `json:"secret_export"`
}

type ReconcilePoliciesReq struct {
	ApplicationInstanceID string       `path:"id"`
	EnterpriseID          string       `json:"enterprise_id"`
	CasdoorPermissionID   string       `json:"casdoor_permission_id"`
	ManifestVersion       uint64       `json:"manifest_version"`
	Policies              []PolicyItem `json:"policies"`
}

type RegisterApplicationReq struct {
	ID           string `json:"id"`
	EnterpriseID string `json:"enterprise_id"`
	Key          string `json:"key"`
	Name         string `json:"name"`
}

type RegisterConnectorReq struct {
	EnterpriseID  string `json:"enterprise_id"`
	ApplicationID string `json:"application_id"`
	InstanceID    string `json:"instance_id"`
	ConnectorKey  string `json:"connector_key"`
}

type RegisterEnterpriseReq struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RegisterInstanceReq struct {
	ApplicationID string `path:"id"`
	EnterpriseID  string `json:"enterprise_id"`
	InstanceKey   string `json:"instance_key"`
	Environment   string `json:"environment,optional"`
	CanonicalURL  string `json:"canonical_url"`
}

type ResolveLegacyIdentityReq struct {
	LegacySource  string `json:"legacy_source"`
	LegacySubject string `json:"legacy_subject"`
}

type ResolveLegacyIdentityResp struct {
	PrincipalID string `json:"principal_id"`
}

type ResolveProductSessionReq struct {
	InstanceID   string `json:"instance_id"`
	SessionToken string `json:"session_token"`
}

type ResolveProductSessionResp struct {
	PrincipalID      string `json:"principal_id"`
	DisplayName      string `json:"display_name"`
	Email            string `json:"email"`
	LegacySubject    string `json:"legacy_subject,optional"`
	Revoked          bool   `json:"revoked"`
	ExpiresAt        int64  `json:"expires_at"`
	LifecycleVersion uint64 `json:"lifecycle_version"`
}

type RevokeProductSessionReq struct {
	InstanceID   string `json:"instance_id"`
	SessionToken string `json:"session_token"`
}

type RevokeSessionReq struct {
	SessionID    string `path:"id"`
	EnterpriseID string `json:"enterprise_id"`
}

type RoleBindingIDReq struct {
	ApplicationInstanceID string `path:"id"`
	BindingID             string `path:"bindingId"`
	EnterpriseID          string `json:"enterprise_id"`
}

type RoleBindingListReq struct {
	ApplicationInstanceID string `path:"id"`
	EnterpriseID          string `form:"enterprise_id"`
}

type RoleBindingListResp struct {
	Items []RoleBindingResp `json:"items"`
}

type RoleBindingReq struct {
	ApplicationInstanceID string              `path:"id"`
	EnterpriseID          string              `json:"enterprise_id"`
	SubjectType           string              `json:"subject_type"`
	SubjectID             string              `json:"subject_id"`
	Role                  string              `json:"role"`
	Resource              RoleBindingResource `json:"resource"`
}

type RoleBindingResource struct {
	Type string `json:"type"`
	ID   string `json:"id"`
}

type RoleBindingResp struct {
	ID          string              `json:"id"`
	SubjectType string              `json:"subject_type"`
	SubjectID   string              `json:"subject_id"`
	Role        string              `json:"role"`
	Resource    RoleBindingResource `json:"resource"`
	Status      string              `json:"status"`
}

type RotateCredentialReq struct {
	ID              string `path:"id"`
	Reason          string `json:"reason"`
	LifetimeSeconds int64  `json:"lifetime_seconds"`
}

type SecurityConfigReq struct {
	EnterpriseID          string `form:"enterprise_id"`
	ApplicationInstanceID string `path:"id"`
}

type SecurityConfigResp struct {
	EnterpriseID          string `json:"enterprise_id"`
	ApplicationInstanceID string `json:"application_instance_id"`
	PublicSharing         bool   `json:"public_sharing"`
	ExportEnabled         bool   `json:"export_enabled"`
	SecretExport          bool   `json:"secret_export"`
	Version               uint64 `json:"version"`
}

type SessionListReq struct {
	EnterpriseID string `form:"enterprise_id"`
}

type SessionListResp struct {
	Sessions []SessionSummaryResp `json:"sessions"`
}

type SessionSummaryResp struct {
	ID                    string `json:"id"`
	EnterpriseID          string `json:"enterprise_id"`
	PrincipalID           string `json:"principal_id"`
	ApplicationInstanceID string `json:"application_instance_id,optional"`
	Kind                  string `json:"kind"`
	ExpiresAt             int64  `json:"expires_at"`
	Revoked               bool   `json:"revoked"`
	CSRFToken             string `json:"csrf_token,optional"`
}

type SyncDirectoryGroupReq struct {
	ExternalID   string   `path:"externalId"`
	EnterpriseID string   `json:"enterprise_id"`
	Provider     string   `json:"provider"`
	Name         string   `json:"name"`
	PrincipalIDs []string `json:"principal_ids"`
}

type VersionResp struct {
	Version    string `json:"version"`
	APIVersion string `json:"api_version"`
}
